FROM python:3

RUN curl -O https://raw.githubusercontent.com/home-assistant-libs/pytradfri/master/script/install-coap-client.sh

RUN chmod +x install-coap-client.sh && ./install-coap-client.sh

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

ENV PYTHONUNBUFFERED=1

CMD ["python", "src/main.py"]
